{% set name = "wagtail-knowledgebase" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wagtail-knowledgebase-{{ version }}.tar.gz
  sha256: d27f7ed855f43bd8c1272da22b12465a945486c7a68e0d36abedb11a2bdcbbb4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - wagtail >=5.0.0

test:
  imports:
    - wtknowledgebase
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/skruger/wagtail-knowledgebase
  summary: Knowledgebase pages with bootstrap compatible StreamFields configured
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
